# Generated by Django 5.2.9 on 2026-01-11 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_technology_project_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
    ]
